"""Rendering a :class:`ScoringMemo` for Telegram and for a downloadable file."""

from __future__ import annotations

import datetime as dt

from .scoring import RECOMMENDATION_LABELS, ScoringMemo

TELEGRAM_LIMIT = 4096


def score_bar(score: int, width: int = 10) -> str:
    return "█" * score + "░" * (width - score)


def render_markdown(memo: ScoringMemo, generated_at: dt.datetime | None = None) -> str:
    """The full memo, as a Markdown document."""
    stamp = (generated_at or dt.datetime.now(dt.timezone.utc)).strftime("%Y-%m-%d %H:%M UTC")
    overall = memo.weighted_score()

    out: list[str] = [
        f"# Scoring memo — {memo.company_name}",
        "",
        f"*{memo.one_liner}*",
        "",
        f"**Stage:** {memo.stage}  |  **Sector:** {memo.sector}  |  **Generated:** {stamp}",
        "",
        f"## Recommendation: {RECOMMENDATION_LABELS.get(memo.recommendation, memo.recommendation)}",
        "",
        f"**Overall score: {overall}/10**  |  **Conviction: {memo.conviction}**",
        "",
        memo.recommendation_rationale,
        "",
        "## Summary",
        "",
        memo.summary,
        "",
        "## Scores",
        "",
        "| Dimension | Weight | Score | Weighted |",
        "| --- | ---: | ---: | ---: |",
    ]

    for _, label, weight, dim in memo.dimensions():
        out.append(f"| {label} | {weight:.0%} | {dim.score}/10 | {weight * dim.score:.2f} |")
    out += ["| **Total** | **100%** | | " + f"**{overall}/10** |", ""]

    out += ["## Dimension detail", ""]
    for _, label, weight, dim in memo.dimensions():
        out += [f"### {label} — {dim.score}/10 (weight {weight:.0%})", "", dim.rationale, ""]
        if dim.evidence:
            out.append("**Evidence:**")
            out += [f"- {item}" for item in dim.evidence]
            out.append("")
        if dim.gaps:
            out.append("**Gaps:**")
            out += [f"- {item}" for item in dim.gaps]
            out.append("")

    if memo.key_strengths:
        out += ["## Key strengths", ""] + [f"- {item}" for item in memo.key_strengths] + [""]

    if memo.key_risks:
        out += ["## Key risks", ""]
        for risk in memo.key_risks:
            out.append(f"- **[{risk.severity.upper()}]** {risk.risk}")
            out.append(f"  - *Mitigation / disconfirming test:* {risk.mitigation}")
        out.append("")

    if memo.diligence_questions:
        out += ["## Diligence questions", ""]
        out += [f"{i}. {q}" for i, q in enumerate(memo.diligence_questions, start=1)]
        out.append("")

    if memo.missing_information:
        out += ["## Missing information", ""]
        out += [f"- {item}" for item in memo.missing_information]
        out.append("")

    out += [
        "---",
        "",
        "*Generated by a VC analyst bot from founder-supplied materials. "
        "Claims in the source material are not independently verified.*",
    ]
    return "\n".join(out)


def render_chat(memo: ScoringMemo) -> str:
    """The at-a-glance version posted into the chat."""
    overall = memo.weighted_score()
    lines = [
        f"📋 {memo.company_name} — {memo.one_liner}",
        f"{memo.stage} · {memo.sector}",
        "",
        f"🎯 {RECOMMENDATION_LABELS.get(memo.recommendation, memo.recommendation)}",
        f"Overall {overall}/10 · conviction: {memo.conviction}",
        "",
        "SCORES",
    ]
    for _, label, weight, dim in memo.dimensions():
        lines.append(f"{score_bar(dim.score)} {dim.score:>2}/10  {label} ({weight:.0%})")

    lines += ["", "WHY", memo.recommendation_rationale]

    if memo.key_risks:
        lines += ["", "TOP RISKS"]
        for risk in memo.key_risks[:3]:
            lines.append(f"• [{risk.severity.upper()}] {risk.risk}")

    if memo.diligence_questions:
        lines += ["", "ASK THE FOUNDERS"]
        for question in memo.diligence_questions[:3]:
            lines.append(f"• {question}")

    lines += ["", "Full memo attached as a file. 📎"]
    return "\n".join(lines)


def chunk(text: str, limit: int = TELEGRAM_LIMIT) -> list[str]:
    """Split text into Telegram-sized pieces, preferring paragraph then line breaks."""
    if len(text) <= limit:
        return [text]

    chunks: list[str] = []
    remaining = text
    while len(remaining) > limit:
        window = remaining[:limit]
        split_at = window.rfind("\n\n")
        if split_at < limit // 2:
            split_at = window.rfind("\n")
        if split_at < limit // 2:
            split_at = limit
        chunks.append(remaining[:split_at].rstrip())
        remaining = remaining[split_at:].lstrip("\n")
    if remaining:
        chunks.append(remaining)
    return chunks


def filename_for(memo: ScoringMemo) -> str:
    safe = "".join(c if c.isalnum() or c in "-_ " else "" for c in memo.company_name).strip()
    safe = safe.replace(" ", "_") or "company"
    date = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%d")
    return f"{safe}_scoring_memo_{date}.md"
